// automatically generated by the FlatBuffers compiler, do not modify

namespace fb
{

public enum Command : int
{
 MATCH_REQUEST = 0,
 MATCH_RESPONSE = 1,
 LATENCY = 2,
 HEALTH_CHECK = 3,
 MSLIST_REQUEST = 4,
 MSLIST_RESPONSE = 5,
 PG_START = 6,
 PG_END = 7,
 PG_DUMMY = 8,
 ROOM_CREATE_REQUEST = 9,
 ROOM_CREATE_RESPONSE = 10,
 ROOM_JOIN_REQUEST = 11,
 ROOM_JOIN_RESPONSE = 12,
 GAME_START = 13,
 GAME_END = 14,
};


}
